"""
Co-deletion explorer page layout with tabbed interface.

This module contains the layout for the interactive co-deletion analysis page,
with separate tabs for each main visualization type.
"""

from dash import dcc, html
import dash_bootstrap_components as dbc


def create_codeletion_layout():
    """
    Create the co-deletion explorer layout with tabs for each visualization.
    
    Returns:
        Dash layout component for the co-deletion page
    """
    layout = dbc.Container([
        # Header with back button
        dbc.Row([
            dbc.Col([
                dcc.Link(
                    dbc.Button("← Home", color="secondary", outline=True, size="sm", className="mb-3"),
                    href="/"
                ),
                html.H1(
                    "Co-Deletion Explorer",
                    className="text-center mb-4"
                ),
                html.P(
                    "Interactive visualization of conditional co-deletion probabilities "
                    "across chromosomes and TCGA PanCancer Atlas studies.",
                    className="text-center text-muted mb-4"
                )
            ])
        ]),
        
        # Tabs for different visualizations
        dbc.Row([
            dbc.Col([
                dbc.Tabs([
                    dbc.Tab(label="Individual Gene Deletions", tab_id="tab-deletion-freq"),
                    dbc.Tab(label="Co-Deletion Heatmap", tab_id="tab-heatmap"),
                    dbc.Tab(label="Top Gene Pairs", tab_id="tab-gene-pairs"),
                    dbc.Tab(label="Distance vs Probability", tab_id="tab-distance-scatter"),
                    dbc.Tab(label="Synthetic Lethality Targets", tab_id="tab-target-discovery"),
                ], id="visualization-tabs", active_tab="tab-heatmap", className="mb-4")
            ])
        ]),
        
        # Tab content
        html.Div(id="tab-content"),
        
        # Footer
        dbc.Row([
            dbc.Col([
                html.Hr(),
                html.Div(
                    children=[
                        html.P(
                            [
                                "Data source: ",
                                html.A("cBioPortal for Cancer Genomics", 
                                       href="https://www.cbioportal.org/", 
                                       target="_blank"),
                                " | TCGA PanCancer Atlas 2018"
                            ],
                            className="text-center text-muted small"
                        ),
                        html.P(
                            [
                                "The results shown here are in whole or part based upon data generated by the TCGA Research Network: ",
                                html.A("https://www.cancer.gov/tcga",
                                       href="https://www.cancer.gov/tcga",
                                       target="_blank")
                            ],
                            className="text-center text-muted small"
                        ),
                        html.P(
                            [
                                "Synthetic lethality data: Harle et al. (2025). ",
                                html.A("A compendium of synthetic lethal gene pairs defined by extensive combinatorial pan-cancer CRISPR screening",
                                       href="https://doi.org/10.1186/s13059-025-03737-w",
                                       target="_blank"),
                                ". Genome Biology."
                            ],
                            className="text-center text-muted small"
                        ),
                        html.P(
                            [
                                "Created by Trevor A. Zandi | ",
                                html.A("GitHub",
                                       href="https://github.com/TrevorZandi/TCGA-Codeletion",
                                       target="_blank")
                            ],
                            className="text-center text-muted small"
                        )
                    ]
                )
            ])
        ])
        
    ], fluid=True, style={'maxWidth': '1400px'})
    
    return layout


def create_deletion_freq_tab():
    """Create the Individual Gene Deletion Frequencies tab content."""
    return dbc.Row([
        # Controls
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("Visualization Controls")),
                dbc.CardBody([
                    html.Label("TCGA, PanCancer Atlas Study:", className="fw-bold"),
                    dcc.Dropdown(
                        id='deletion-study-dropdown',
                        options=[],
                        value=None,
                        clearable=False,
                        className="mb-3"
                    ),
                    html.Label("Chromosome:", className="fw-bold"),
                    dcc.Dropdown(
                        id='deletion-chromosome-dropdown',
                        options=[
                            *[{'label': f'Chromosome {i}', 'value': str(i)} for i in range(1, 23)],
                            {'label': 'Chromosome X', 'value': 'X'},
                            {'label': 'Chromosome Y', 'value': 'Y'}
                        ],
                        value='13',
                        clearable=False,
                        className="mb-3"
                    ),
                    html.Label("Filter by Gene:", className="fw-bold"),
                    dcc.Input(
                        id='deletion-gene-filter',
                        type='text',
                        placeholder='Enter gene symbol (optional)',
                        className="form-control mb-3",
                        debounce=True
                    ),
                    html.Label("Min Deletion Frequency:", className="fw-bold"),
                    dcc.Input(
                        id='deletion-min-freq',
                        type='number',
                        min=0,
                        max=1,
                        step=0.01,
                        placeholder='0-1',
                        className="form-control mb-3",
                        debounce=True
                    ),
                ])
            ], className="mb-4")
        ], width=12, lg=3),
        
        # Visualization
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("Individual Gene Deletion Frequencies")),
                dbc.CardBody([
                    html.Div(id='deletion-stats-display', className="mb-3"),
                    dcc.Loading(
                        id="loading-deletion-scatter",
                        type="default",
                        children=dcc.Graph(
                            id='deletion-frequency-scatter',
                            config={
                                'displayModeBar': True,
                                'displaylogo': False
                            }
                        )
                    )
                ])
            ])
        ], width=12, lg=9)
    ])


def create_heatmap_tab():
    """Create the Co-Deletion Heatmap tab content."""
    return dbc.Row([
        # Controls
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("Visualization Controls")),
                dbc.CardBody([
                    html.Label("TCGA, PanCancer Atlas Study:", className="fw-bold"),
                    dcc.Dropdown(
                        id='heatmap-study-dropdown',
                        options=[],
                        value=None,
                        clearable=False,
                        className="mb-3"
                    ),
                    html.Label("Chromosome:", className="fw-bold"),
                    dcc.Dropdown(
                        id='heatmap-chromosome-dropdown',
                        options=[
                            *[{'label': f'Chromosome {i}', 'value': str(i)} for i in range(1, 23)],
                            {'label': 'Chromosome X', 'value': 'X'},
                            {'label': 'Chromosome Y', 'value': 'Y'}
                        ],
                        value='13',
                        clearable=False,
                        className="mb-3"
                    ),
                    html.Label("Colorscale:", className="fw-bold"),
                    dcc.Dropdown(
                        id='heatmap-colorscale-dropdown',
                        options=[
                            {'label': 'Viridis', 'value': 'Viridis'},
                            {'label': 'YlOrRd (Yellow-Orange-Red)', 'value': 'YlOrRd'},
                            {'label': 'Blues', 'value': 'Blues'},
                            {'label': 'Reds', 'value': 'Reds'},
                            {'label': 'RdBu (Red-Blue)', 'value': 'RdBu'},
                            {'label': 'Plasma', 'value': 'Plasma'},
                        ],
                        value='Viridis',
                        clearable=False,
                        className="mb-3"
                    ),
                    html.Label("Number of axis labels:", className="fw-bold"),
                    dcc.Slider(
                        id='heatmap-n-labels-slider',
                        min=5,
                        max=50,
                        step=5,
                        value=20,
                        marks={i: str(i) for i in range(5, 51, 5)},
                        tooltip={"placement": "bottom", "always_visible": True}
                    ),
                ])
            ], className="mb-4")
        ], width=12, lg=3),
        
        # Visualization
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("Conditional Co-Deletion Heatmap")),
                dbc.CardBody([
                    html.Div(id='heatmap-stats-display', className="mb-3"),
                    dcc.Loading(
                        id="loading-heatmap",
                        type="default",
                        children=dcc.Graph(
                            id='codeletion-heatmap',
                            config={
                                'displayModeBar': True,
                                'displaylogo': False,
                                'toImageButtonOptions': {
                                    'format': 'png',
                                    'filename': 'chr13_codeletion_heatmap',
                                    'height': 1200,
                                    'width': 1200,
                                    'scale': 2
                                }
                            }
                        )
                    )
                ])
            ])
        ], width=12, lg=9)
    ])


def create_gene_pairs_tab():
    """Create the Top Gene Pairs tab content."""
    return dbc.Row([
        # Controls
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("Visualization Controls")),
                dbc.CardBody([
                    html.Label("TCGA, PanCancer Atlas Study:", className="fw-bold"),
                    dcc.Dropdown(
                        id='pairs-study-dropdown',
                        options=[],
                        value=None,
                        clearable=False,
                        className="mb-3"
                    ),
                    html.Label("Chromosome:", className="fw-bold"),
                    dcc.Dropdown(
                        id='pairs-chromosome-dropdown',
                        options=[
                            *[{'label': f'Chromosome {i}', 'value': str(i)} for i in range(1, 23)],
                            {'label': 'Chromosome X', 'value': 'X'},
                            {'label': 'Chromosome Y', 'value': 'Y'}
                        ],
                        value='13',
                        clearable=False,
                        className="mb-3"
                    ),
                    html.Label("Search for specific gene:", className="fw-bold"),
                    dcc.Input(
                        id='pairs-gene-search-input',
                        type='text',
                        placeholder='Enter gene name...',
                        className="form-control mb-3",
                        debounce=True
                    ),
                    html.Label("Number of top pairs:", className="fw-bold"),
                    dcc.Slider(
                        id='pairs-n-pairs-slider',
                        min=10,
                        max=50,
                        step=5,
                        value=20,
                        marks={i: str(i) for i in range(10, 51, 10)},
                        tooltip={"placement": "bottom", "always_visible": True},
                        className="mb-3"
                    ),
                    html.Hr(),
                    html.Label("Filters:", className="fw-bold"),
                    html.Label("Min Distance (bp):", className="small"),
                    dcc.Input(
                        id='pairs-min-distance',
                        type='number',
                        placeholder='e.g., 1000000',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Max Distance (bp):", className="small"),
                    dcc.Input(
                        id='pairs-max-distance',
                        type='number',
                        placeholder='e.g., 50000000',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Min Freq:", className="small"),
                    dcc.Input(
                        id='pairs-min-freq',
                        type='number',
                        min=0,
                        max=1,
                        step=0.01,
                        placeholder='0-1',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Min P(A|B):", className="small"),
                    dcc.Input(
                        id='pairs-min-pab',
                        type='number',
                        min=0,
                        max=1,
                        step=0.01,
                        placeholder='0-1',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Min P(B|A):", className="small"),
                    dcc.Input(
                        id='pairs-min-pba',
                        type='number',
                        min=0,
                        max=1,
                        step=0.01,
                        placeholder='0-1',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Min P(A,B):", className="small"),
                    dcc.Input(
                        id='pairs-min-joint',
                        type='number',
                        min=0,
                        max=1,
                        step=0.01,
                        placeholder='0-1',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                ])
            ], className="mb-4")
        ], width=12, lg=3),
        
        # Visualization
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("Top Co-deleted Gene Pairs")),
                dbc.CardBody([
                    dcc.Loading(
                        id="loading-pairs-table",
                        type="default",
                        children=html.Div(id='top-pairs-table')
                    )
                ])
            ])
        ], width=12, lg=9)
    ])


def create_distance_scatter_tab():
    """Create the Distance vs Probability tab content."""
    return dbc.Row([
        # Controls
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("Visualization Controls")),
                dbc.CardBody([
                    html.Label("TCGA, PanCancer Atlas Study:", className="fw-bold"),
                    dcc.Dropdown(
                        id='scatter-study-dropdown',
                        options=[],
                        value=None,
                        clearable=False,
                        className="mb-3"
                    ),
                    html.Label("Chromosome:", className="fw-bold"),
                    dcc.Dropdown(
                        id='scatter-chromosome-dropdown',
                        options=[
                            *[{'label': f'Chromosome {i}', 'value': str(i)} for i in range(1, 23)],
                            {'label': 'Chromosome X', 'value': 'X'},
                            {'label': 'Chromosome Y', 'value': 'Y'}
                        ],
                        value='13',
                        clearable=False,
                        className="mb-3"
                    ),
                    html.Label("Filter by Gene A:", className="fw-bold"),
                    dcc.Input(
                        id='scatter-gene-filter',
                        type='text',
                        placeholder='Enter gene symbol...',
                        className='form-control mb-3',
                        debounce=True
                    ),
                    html.Hr(),
                    html.Label("Filters:", className="fw-bold"),
                    html.Label("Min Freq(A):", className="small"),
                    dcc.Input(
                        id='scatter-min-freq-a',
                        type='number',
                        min=0,
                        max=1,
                        step=0.01,
                        placeholder='0-1',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Max Freq(A):", className="small"),
                    dcc.Input(
                        id='scatter-max-freq-a',
                        type='number',
                        min=0,
                        max=1,
                        step=0.01,
                        placeholder='0-1',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Min Distance (bp):", className="small"),
                    dcc.Input(
                        id='scatter-min-distance',
                        type='number',
                        placeholder='e.g., 1000000',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Max Distance (bp):", className="small"),
                    dcc.Input(
                        id='scatter-max-distance',
                        type='number',
                        placeholder='e.g., 50000000',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Min P(B|A):", className="small"),
                    dcc.Input(
                        id='scatter-min-pba',
                        type='number',
                        min=0,
                        max=1,
                        step=0.01,
                        placeholder='0-1',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                    html.Label("Max P(B|A):", className="small"),
                    dcc.Input(
                        id='scatter-max-pba',
                        type='number',
                        min=0,
                        max=1,
                        step=0.01,
                        placeholder='0-1',
                        className="form-control form-control-sm mb-2",
                        debounce=True
                    ),
                ])
            ], className="mb-4")
        ], width=12, lg=3),
        
        # Visualization
        dbc.Col([
            dbc.Card([
                dbc.CardHeader(html.H5("Genomic Distance vs Co-deletion Probability")),
                dbc.CardBody([
                    html.P(
                        "This scatter plot shows the relationship between physical distance "
                        "and conditional co-deletion probability P(B|A). Each point represents "
                        "a gene pair where P(B|A) > 0. The x-axis uses a logarithmic scale.",
                        className="text-muted small mb-3"
                    ),
                    dcc.Loading(
                        id="loading-distance-scatter",
                        type="default",
                        children=dcc.Graph(
                            id='distance-frequency-scatter',
                            config={
                                'displayModeBar': True,
                                'displaylogo': False
                            }
                        )
                    )
                ])
            ])
        ], width=12, lg=9)
    ])


def create_stats_display(n_genes, n_genes_with_deletions, max_deletion_pct, chromosome="13"):
    """
    Create statistics display component.
    
    Args:
        n_genes: Number of genes on the chromosome
        n_genes_with_deletions: Number of genes deleted at least once
        max_deletion_pct: Maximum individual gene deletion frequency (as percentage)
        chromosome: Chromosome identifier (default: "13")
        
    Returns:
        HTML component with statistics
    """
    return html.Div([
        dbc.Row([
            dbc.Col([
                html.Div([
                    html.H4(str(n_genes), className="text-primary mb-0"),
                    html.P(f"Genes on Chr{chromosome}", className="text-muted small mb-0")
                ], className="text-center")
            ], width=4),
            dbc.Col([
                html.Div([
                    html.H4(str(n_genes_with_deletions), className="text-primary mb-0"),
                    html.P("Genes with Deletions", className="text-muted small mb-0")
                ], className="text-center")
            ], width=4),
            dbc.Col([
                html.Div([
                    html.H4(f"{max_deletion_pct}%", className="text-primary mb-0"),
                    html.P("Max Deletion Freq", className="text-muted small mb-0")
                ], className="text-center")
            ], width=4)
        ])
    ])
